name: vibe_notes
description: A minimalist voice note app with AI capabilities.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  shared_preferences: ^2.0.15
  path_provider: ^2.0.15
  record: ^4.4.4
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
